steps:
  - label: "Build Project"
    env:
      PATH: "$PATH:/var/lib/buildkite-agent/apache-maven-3.6.3/bin:/var/lib/buildkite-agent:/usr/local/bin"
      AWS_PROFILE: "buildkite"
    command: "mvn package"
    artifact_paths: "target/*.jar"
  - label: "Build Image"
    command: "docker build --tag karthikkrish84/myjavaapp ."
    plugins:
      - artifacts#v1.8.0:
          download: "target/*.jar"
  - label: "Push Image"
    command: "docker push karthikkrish84/myjavaapp:latest"
  - label: "Deploy"
    commands:
      - "git clone git@github.com:karthikkrish84/GKE-deployment-files.git"
      - "cd GKE-deployment-files/java"
      - "kubectl apply -f java-deployment.yaml -n awsproject"
      - "kubectl apply -f java-service.yaml -n awsproject"
      - "kubectl apply -f java-configmap.yaml -n awsproject"
      - "kubectl create secret generic javaapp --from-literal=SQL_PASSWORD=kihtrak -n awsproject"
      - "kubectl apply -f java-hpa.yaml -n awsproject"