steps:
  - label: "Build Project"
    command: " mvn package"
    artifact_paths: "target/*.jar"
  - label: "Build Image"
    command: "docker build --tag karthikkrish84/myjavaapp ."
    plugins:
      - artifacts#v1.8.0:
          download: "target/*.jar"
  - label: "Push Image"
    command: "docker push karthikkrish84/myjavaapp:latest"
  - label: "Deploy"
    commands:
      - "echo $PATH"
      - "java -version"